FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y net-tools nmap wget nano curl

# download and install Elasticsearch and Kibana
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.9-amd64.deb && \
    dpkg -i elasticsearch-7.17.9-amd64.deb && \
    wget https://artifacts.elastic.co/downloads/kibana/kibana-7.17.9-amd64.deb && \
    dpkg -i kibana-7.17.9-amd64.deb && \
    # clean up
    rm elasticsearch-7.17.9-amd64.deb kibana-7.17.9-amd64.deb

# configure Elasticsearch
RUN mkdir -p /etc/elasticsearch && \
    echo 'cluster.name: elk\n\
node.name: elk-1\n\
path.data: /var/lib/elasticsearch\n\
path.logs: /var/log/elasticsearch\n\
network.host: 0.0.0.0\n\
cluster.initial_master_nodes: ["elk-1"]' > /etc/elasticsearch/elasticsearch.yml

# configure Kibana
RUN mkdir -p /etc/kibana && \
    echo 'server.host: "0.0.0.0"' > /etc/kibana/kibana.yml

# expose necessary ports
EXPOSE 9200 5601

# start Elasticsearch and Kibana
CMD ["sh", "-c", "service elasticsearch start && service kibana start && bash"]
